# Generated by Django 3.0.8 on 2020-07-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balanceSpent',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
